/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardHistoryRouteRouteImport } from './routes/_authenticated/dashboard/history/route'
import { Route as AuthenticatedDashboardLiveRouteImport } from './routes/_authenticated/dashboard/live'
import { Route as AuthenticatedDashboardRulesRouteImport } from './routes/_authenticated/dashboard/rules'
import { Route as AuthenticatedDashboardHistoryIndexRouteImport } from './routes/_authenticated/dashboard/history/index'
import { Route as AuthenticatedDashboardHistorySessionIdRouteImport } from './routes/_authenticated/dashboard/history/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHistoryRouteRoute =
  AuthenticatedDashboardHistoryRouteRouteImport.update({
    id: '/dashboard/history',
    path: '/dashboard/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardLiveRoute =
  AuthenticatedDashboardLiveRouteImport.update({
    id: '/dashboard/live',
    path: '/dashboard/live',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRulesRoute =
  AuthenticatedDashboardRulesRouteImport.update({
    id: '/dashboard/rules',
    path: '/dashboard/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHistoryIndexRoute =
  AuthenticatedDashboardHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardHistoryRouteRoute,
  } as any)
const AuthenticatedDashboardHistorySessionIdRoute =
  AuthenticatedDashboardHistorySessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedDashboardHistoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRouteRouteWithChildren
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/rules': typeof AuthenticatedDashboardRulesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/history/$sessionId': typeof AuthenticatedDashboardHistorySessionIdRoute
  '/dashboard/history/': typeof AuthenticatedDashboardHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/rules': typeof AuthenticatedDashboardRulesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/history/$sessionId': typeof AuthenticatedDashboardHistorySessionIdRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/dashboard/history': typeof AuthenticatedDashboardHistoryRouteRouteWithChildren
  '/_authenticated/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/_authenticated/dashboard/rules': typeof AuthenticatedDashboardRulesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/history/$sessionId': typeof AuthenticatedDashboardHistorySessionIdRoute
  '/_authenticated/dashboard/history/': typeof AuthenticatedDashboardHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/history'
    | '/dashboard/live'
    | '/dashboard/rules'
    | '/dashboard/'
    | '/dashboard/history/$sessionId'
    | '/dashboard/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/live'
    | '/dashboard/rules'
    | '/dashboard'
    | '/dashboard/history/$sessionId'
    | '/dashboard/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/callback'
    | '/auth/login'
    | '/_authenticated/dashboard/history'
    | '/_authenticated/dashboard/live'
    | '/_authenticated/dashboard/rules'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/history/$sessionId'
    | '/_authenticated/dashboard/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/history': {
      id: '/_authenticated/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/live': {
      id: '/_authenticated/dashboard/live'
      path: '/dashboard/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof AuthenticatedDashboardLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/rules': {
      id: '/_authenticated/dashboard/rules'
      path: '/dashboard/rules'
      fullPath: '/dashboard/rules'
      preLoaderRoute: typeof AuthenticatedDashboardRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/history/': {
      id: '/_authenticated/dashboard/history/'
      path: '/'
      fullPath: '/dashboard/history/'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardHistoryRouteRoute
    }
    '/_authenticated/dashboard/history/$sessionId': {
      id: '/_authenticated/dashboard/history/$sessionId'
      path: '/$sessionId'
      fullPath: '/dashboard/history/$sessionId'
      preLoaderRoute: typeof AuthenticatedDashboardHistorySessionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardHistoryRouteRoute
    }
  }
}

interface AuthenticatedDashboardHistoryRouteRouteChildren {
  AuthenticatedDashboardHistorySessionIdRoute: typeof AuthenticatedDashboardHistorySessionIdRoute
  AuthenticatedDashboardHistoryIndexRoute: typeof AuthenticatedDashboardHistoryIndexRoute
}

const AuthenticatedDashboardHistoryRouteRouteChildren: AuthenticatedDashboardHistoryRouteRouteChildren =
  {
    AuthenticatedDashboardHistorySessionIdRoute:
      AuthenticatedDashboardHistorySessionIdRoute,
    AuthenticatedDashboardHistoryIndexRoute:
      AuthenticatedDashboardHistoryIndexRoute,
  }

const AuthenticatedDashboardHistoryRouteRouteWithChildren =
  AuthenticatedDashboardHistoryRouteRoute._addFileChildren(
    AuthenticatedDashboardHistoryRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardHistoryRouteRoute: typeof AuthenticatedDashboardHistoryRouteRouteWithChildren
  AuthenticatedDashboardLiveRoute: typeof AuthenticatedDashboardLiveRoute
  AuthenticatedDashboardRulesRoute: typeof AuthenticatedDashboardRulesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardHistoryRouteRoute:
    AuthenticatedDashboardHistoryRouteRouteWithChildren,
  AuthenticatedDashboardLiveRoute: AuthenticatedDashboardLiveRoute,
  AuthenticatedDashboardRulesRoute: AuthenticatedDashboardRulesRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
